export default {
  breakpoints: ['320px', '768px', '1366px'],
  fontSizes: [12, 14, 16, 20, 24, 32],
  colors: {
    brand01: 'var(--color-brand-01)',
    brand02: 'var(--color-brand-02)',
    brand03: 'var(--color-brand-03)',
    divider01: 'var(--color-divider-01)',
    dividerInverse01: 'var(--color-divider-inverse-01)',
    background01: 'var(--color-background-01)',
    footer01: 'var(--color-footer-01)',
    navigation01: 'var(--color-navigation-01)',
    blueBox: 'var(--color-blue-box)',
    textHeading01: 'var(--color-text-heading-01)',
    textEditorial01: 'var(--color-text-editorial-01)',
    textBody01: 'var(--color-text-body-01)',
    textSupport01: 'var(--color-text-support-01)',
    textSupport02: 'var(--color-text-support-02)',
    footerText01: 'var(--color-footer-text-01)',
    footerText02: 'var(--color-footer-text-02)',
    buttonText01: 'var(--color-button-text-01)',
    buttonTextInverse01: 'var(--color-button-text-inverse-01)',
    buttonText02: 'var(--color-button-text-02)',
    buttonTextHover01: 'var(--color-button-text-hover-01)',
    buttonTextHover02: 'var(--color-button-text-hover-02)',
    buttonTextHover03: 'var(--color-button-text-hover-03)',
    errorText01: 'var(--color-error-text-01)',
    errorContainer01: 'var(--color-error-container-01)',
  },
  space: [0, 4, 8, 16, 32, 72, 112, 144],
  fonts: {
    riforma: '"LL Riforma", "Helvetica Neue", Helvetica, Arial, sans-serif',
  },
  fontSizes: [
    'var(--font-scale-0-font-size)',
    'var(--font-scale-1-font-size)',
    'var(--font-scale-2-font-size)',
    'var(--font-scale-3-font-size)',
    'var(--font-scale-4-font-size)',
    'var(--font-scale-5-font-size)',
    'var(--font-scale-6-font-size)',
    'var(--font-scale-7-font-size)',
    'var(--font-scale-8-font-size)',
    'var(--font-scale-9-font-size)',
    'var(--font-scale-10-font-size)',
    'var(--font-scale-11-font-size)',
  ],
  fontWeights: {
    light: 300,
    regular: 400,
    medium: 500,
    bold: 700,
  },
  lineHeights: {
    solid: '1em',
    m: '1.2em',
    l: '1.3em',
    xl: '1.6em',
  },
  letterSpacings: {
    default: 'normal',
    s: '0.01em',
    m: '0.02em',
  },
};
